/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Supplier extends javax.swing.JInternalFrame {

    /**
     * Creates new form Supplier
     */
    public Supplier() throws ClassNotFoundException {
        initComponents();
        Contents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsupid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsupname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsupcity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtsupphone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SUPPLIER TABLE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Supplier_id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("SCompany_Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Supplier_City");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Supplier_Phone");

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier_id", "SCompany_Name", "Supplier_City", "Supplier_Phone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsupid)
                            .addComponent(txtsupname)
                            .addComponent(txtsupcity)
                            .addComponent(txtsupphone, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGap(171, 171, 171)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsupid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsupname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtsupcity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsupphone, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection con1;
    PreparedStatement insert;
    private void Contents() throws ClassNotFoundException
    {
        int c;
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con1 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","admin");
            insert = con1.prepareStatement("select * from supplier");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            

            
            
            DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            Df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v3= new Vector();
                for(int a=0;a<c;a++)
                {
                    v3.add(rs.getString("s_id"));
                    v3.add(rs.getString("scompany_name"));
                    v3.add(rs.getString("s_city"));
                    v3.add(rs.getString("s_phone"));
                    
                    
                    
                }
                Df.addRow(v3);
                
                
            }
            

            
            txtsupid.setText("");
            txtsupname.setText("");
            txtsupcity.setText("");
            txtsupphone.setText("");
            
            
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String proj = txtsupid.getText();
        String name = txtsupname.getText();
        String des = txtsupcity.getText();
//        String sdate = txtsdate.getText();
//        String edate = txtedate.getText();
        String stat = (txtsupphone.getText());
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con1 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","admin");
            
            insert = con1.prepareStatement("insert into supplier(s_id,scompany_name,s_city,s_phone) values('"+proj+"','"+name+"','"+des+"','"+stat+"')");

            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record Added");
            Contents();
            
            txtsupid.setText("");
            txtsupname.setText("");
            txtsupcity.setText("");
//            txtsdate.setText("");
//            txtedate.setText("");
            txtsupphone.setText("");
            
            txtsupid.requestFocus();
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        try {
            String ind = (Df.getValueAt(selectedIndex,0).toString());
            String id = txtsupid.getText();
            String name = txtsupname.getText();
            String phone = txtsupphone.getText();
//            String sdate = txtsdate.getText();
//            String edate = txtedate.getText();
            String city = txtsupcity.getText();
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con1 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","admin");
            insert = con1.prepareStatement("update supplier set scompany_name='"+name+"',s_city='"+city+"',s_phone='"+phone+"' where s_id='"+ind+"' ");

            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record Update");
            Contents();
            
            txtsupid.setText("");
            txtsupname.setText("");
            txtsupphone.setText("");
//            txtsdate.setText("");
//            txtedate.setText("");
            txtsupcity.setText("");
            
            txtsupid.requestFocus();
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        
        try {
            
            
            String ele = (txtsupid.getText());
            if(selectedIndex==-1)
            {
                int dialogResult = JOptionPane.showConfirmDialog(null,"Do you what to Delete the Record","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_NO_OPTION)
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                con1 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","admin");
                insert = con1.prepareStatement("delete from supplier where s_id='"+ele+"' ");
                insert.executeUpdate();
            
                JOptionPane.showMessageDialog(this,"Record Deleted");
                Contents();
            
                
                txtsupid.setText("");
                txtsupname.setText("");
                txtsupphone.setText("");
//                txtsdate.setText("");
//                txtedate.setText("");
                txtsupcity.setText("");
                txtsupid.requestFocus();
                
            
            }
            }
            else{
                String ind = (Df.getValueAt(selectedIndex,0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(null,"Do you what to Delete the Record","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_NO_OPTION)
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                con1 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","admin");
                insert = con1.prepareStatement("delete from supplier where s_id='"+ind+"' ");
                insert.executeUpdate();
            
                JOptionPane.showMessageDialog(this,"Record Deleted");
                Contents();
            
                txtsupid.setText("");
                txtsupname.setText("");
                txtsupphone.setText("");
//                txtsdate.setText("");
//                txtedate.setText("");
                txtsupcity.setText("");
                
                txtsupid.requestFocus();
            
            }
            }
            
            
            
             
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        if(selectedIndex!=-1){
        txtsupid.setText(Df.getValueAt(selectedIndex, 0).toString());
        txtsupname.setText(Df.getValueAt(selectedIndex, 1).toString());
        txtsupcity.setText(Df.getValueAt(selectedIndex, 2).toString());
//        txtsdate.setText(Df.getValueAt(selectedIndex, 3).toString());
//        txtedate.setText(Df.getValueAt(selectedIndex, 4).toString());
        txtsupphone.setText(Df.getValueAt(selectedIndex, 3).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtsupcity;
    private javax.swing.JTextField txtsupid;
    private javax.swing.JTextField txtsupname;
    private javax.swing.JTextField txtsupphone;
    // End of variables declaration//GEN-END:variables
}
